MarsyApparel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import create_product_flutter, show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id 
from main.views import register, login_user, logout_user, delete_product, increment_product, decrement_product,edit_product, get_product_json, add_product_ajax, delete_product_ajax



app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete-product/<int:product_id>/', delete_product, name='delete_product'),
    path('increment-product/<int:product_id>/', increment_product, name='increment_product'),
    path('decrement-product/<int:product_id>/', decrement_product, name='decrement_product'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete-product-ajax/<int:product_id>/', delete_product_ajax, name='delete_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),


]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ProductForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

main/views.py
import datetime
import json
from django.http import HttpResponseRedirect, JsonResponse
from main.forms import ProductForm
from django.urls import reverse
from django.shortcuts import render
from main.models import Item
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/login')
def show_main(request):
    products = Item.objects.filter(user=request.user)
    item_counter = products.count()
    context = {
        'name': request.user.username,
        'class': 'PBP E', 
        'products': products,
        'last_login': request.COOKIES.get('last_login'),
        'item_counter' : item_counter,

    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    context = {'form': form}
    return render(request, "create_product.html", context)

def delete_product(request, product_id):
    product = get_object_or_404(Item, pk=product_id)
    
    if product.user == request.user:
        product.delete()
    
    return HttpResponseRedirect(reverse('main:show_main'))

def increment_product(request, product_id):
    product = get_object_or_404(Item, pk=product_id)
    
    if product.user == request.user:
        product.amount += 1
        product.save()
    
    return HttpResponseRedirect(reverse('main:show_main'))

def decrement_product(request, product_id):
    product = get_object_or_404(Item, pk=product_id)
    
    if product.user == request.user:
        if product.amount > 1:
            product.amount -= 1
            product.save()
    
    return HttpResponseRedirect(reverse('main:show_main'))

def login_user(request):
    if request.method == 'POST':
    
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def edit_product(request, id):
    product = Item.objects.get(pk = id)

    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def get_product_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Item(name=name, amount=amount, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()


@csrf_exempt
def delete_product_ajax(request, product_id):
    if request.method == 'POST':
        try:
            product = Item.objects.get(id=product_id)
            product.delete()
            return HttpResponse("OK", status=200)
        except Item.DoesNotExist:
            return HttpResponse("Produk tidak ada", status=404)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<head>
    <meta charset="UTF-8">

    <title style="font-family: 'Mulish';">Edit Product</title>

    <style>
        body {
            font-family: "Mulish";
            background-image: url(https://i.pinimg.com/564x/97/48/ca/9748ca48a8162ad52f53030c57049b05.jpg);
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: scroll;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .edit_product{
            background-color: #fffdfc;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px 20px 20px 20px;
            max-width: 600px;
            width: 100%;
            text-align: center;
        }
        .edit_product h1 {
            margin-bottom: 20px;

        }
        .edit_product-form {
            margin-bottom: 15px;
            padding: 20px 20px 20px 20px;
        }
        .edit_product-form table{
            margin-bottom: 15px;
            padding: 20px 20px 20px 20px;
        }

        </style>
        <link href="https://fonts.googleapis.com/css2?family=Mulish&family=Unna:wght@700&display=swap" rel="stylesheet">

</head>

<body>
    <div class = "edit_product">
        <h1>Edit Product</h1>
        
        <div class="edit_product-form">
            <form method="POST">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td>
                            <input type="submit" value="Edit Product"/>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</body>


{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">

    <title style="font-family: 'Mulish';">Login</title>
    <style>
        body {
            font-family: "Mulish";
            background-color: #ebe6e4;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .login {
            background-color: #fffdfc;
            border-radius: 5px;
            box-shadow: 0 0 10px 292727(0, 0, 0, 0.1);
            padding: 20px;
            max-width: 400px;
            width: 100%;
            text-align: center;
        }

        .login-container h1 {
            margin-bottom: 20px;
        }

        .login-form {
            text-align: center;
            padding: auto;
        }

        .form-group {
            margin-bottom: 15px;
            padding: auto;
        }

        .form-group label {
            display: block;
            margin-bottom: 5px;
        }

        .form-group input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .form-group button {
            background-color: #007BFF;

        }

        </style>
        <link href="https://fonts.googleapis.com/css2?family=Mulish&family=Unna:wght@700&display=swap" rel="stylesheet">


</head>

<body>

    <div class = "login">

        <h1>Login</h1>

        <div class="login-form">
            <form method="POST" action="">
            {% csrf_token %}

            <table>
                <div class = "form-group">
                    <tr>
                        <td><label>Username: </label></td>
                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>
                </div>   
                <div class = "form-group">
                    <tr>
                        <td><label>Password: </label></td>
                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>
                </div>   
                <div class = "form-group">
                    <tr>
                        <td></td>
                        <td><input class="btn login_btn" type="submit" value="Login" style="background-color: #7fd2e0; border-radius: 5px"></td>
                    </tr>
                </div>   

            </table>
        </form>
        </div>

        <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
    </div>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
</body> 

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

    <head>
        <nav class="navbar" style="background-color: #ebe6e4;">
            <div class="logo" style="color: #292727;">
                <a style="padding: 0px 15px 0px 15px;"><img src="https://i.pinimg.com/736x/ad/5a/d2/ad5ad2e05f522b2865690d7389d5ff68.jpg"style="width: 70px; height: 70px; margin-right: 10px;"></a>
                <a style="padding: 9px 0px 9px 0px;">Marsy Apparel</a>            </div>
            <div class="menu">
                <ul>
                    <li>
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#">Sales Overview</a>
                    </li>
                    <li>
                        <a href="#">Contacts</a>
                    </li>
                    <li>
                        <a href="{% url 'main:logout' %}" class="ml-auto">
                        <button class="btn btn-outline-danger" type="button">Logout</button>
                        </a>
                    </li>
                </ul>            
            </div>
        </nav>

    
        <p></p>

        <style>
            .navbar{
                margin: auto;
                position: relative;
            }

            .logo a{
                font-size: 35px;
                font-weight:normal;
                float: left;
                font-family: 'Unna', serif, cursive;
                text-align: center;
            }
            .menu{
                float: right;                
            }

            button{
                background-color: rgb(245, 238, 220);
                border-radius: 5px;
            }

            button:hover {
                box-shadow: -1px 3px 10px 0px rgba(0, 0, 0, 0.8);
            }

            nav{
                width: 100%;
                margin:auto;
                display: flex;
                line-height: 50px;
                position: sticky;
                top:0;
            }
            nav ul{
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
            }
            nav ul li{
                float: left;
            }
            nav ul li a{
                color: #292727;
                font-weight:normal;
                text-align: center;
                padding: 0px 16px 0px 16px;
                text-decoration: none;
            }
            nav ul li a:hover{
                text-decoration: underline;
            }
            section {
                max-width: 1200px; 
                margin: 0 auto;
                padding: 20px;
                text-align: center;
                display: grid;
                grid-template-columns: repeat(4, 1fr);
                gap: 20px;
            }
            .card {
                border: 1px solid #ebe6e4;
                border-radius: 10px;
                padding: 20px;
                margin: 10px;
                box-shadow: 0px 1px 2px 0px rgba(0, 0, 0, 0.4);
                transition: all 0.25s linear;
            }
            
            .card:hover {
                box-shadow: -1px 10px 29px 0px rgba(0, 0, 0, 0.8);
            }

            
            .card img {
                width: 100%;
                border-top-left-radius: 5px;
                border-top-right-radius: 5px;
            }
            
            .card h1 {
                font-family: "IBM Plex Sans", sans-serif;
                font-weight: 50;
                text-transform: uppercase;
                font-size: 20px;
                margin-top: 10px;
            }
            
            .card p {
                font-size: 16px;
                overflow: hidden;
                text-overflow: ellipsis;
            }
        </style>
    </head>

<body style="display: flex; flex-direction: column; align-items: center; text-align: center;">
    <a class="welcome" style="color: #313131; font-family: 'Mulish'; font-size: 24px; text-decoration: none; margin-top: 20px;">-* Hello, {{ name }} *-</a>
    <p style="font-family: 'Mulish';"> Here are <b>{{ item_counter }}</b> available clothing on stock</p>

    <div id="product_cards" class="card"></div>

    <!-- Membuat modal untuk tampilan add Product -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
                </div>
            </div>
        </div>
    </div>
    
    <br />
    <script>
        async function getProducts() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
        }
    

        async function refreshProducts() {
            const productCards = document.getElementById("product_cards");
            productCards.innerHTML = ""; // Clear existing cards

            const products = await getProducts();
            let cardRow = null;

            products.forEach((item, index) => {
                if (index % 3 === 0) {
                    cardRow = document.createElement("div");
                    cardRow.classList.add("row");
                }

                const card = document.createElement("div");
                card.classList.add("card", "col-md-3", "mb-3");
                card.setAttribute('data-product-id', item.id);
                card.innerHTML = `
                    <img src="https://media.theeverygirl.com/wp-content/uploads/2021/01/the-everygirl-questions-to-ask-while-cleaning-out-your-closet-gallery.jpg" alt="Product Image">
                    <h1>${item.fields.name}</h1>
                    <div class="item_amount">
                            <a type="button" style="border: none; text-decoration: none; color: #313131; background-color: rgb(245, 238, 220); border-radius: 5px;" href="decrement-product/${item.pk}"> - </a>
                            <a style="background-color: rgb(235, 224, 210); background-size: 7px; font-size: larger;">.     ${item.fields.amount}     .</a>
                            <a type="button" style="border: none; text-decoration: none; color: #313131; background-color: rgb(245, 238, 220); border-radius: 5px;" href="increment-product/${item.pk}"> + </a>
                    </div>
                    <div>
                        <a>${item.fields.description}</a>
                        <p></p>

                        <button class="btn btn-danger" onclick="deleteProduct(${item.pk})">Delete</button>
                    </div>
                `;

                cardRow.appendChild(card);
                productCards.appendChild(cardRow);
            });
        }
        refreshProducts();

        function addProduct() {
            fetch("{% url 'main:add_product_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)

            window.location.reload();
            document.getElementById("form").reset()

            return false
        }

        document.getElementById("button_add").onclick = addProduct
        
        async function deleteProduct(productId) {
        const response = await fetch(`{% url 'main:delete_product_ajax' 0 %}`.replace("0", productId), {
            method: "POST",
        });

        if (response.status === 200) {
            refreshProducts();
        } else if (response.status === 404) {
            console.log("Produk tidak ada");
        } else {
            console.log("Error deleting product");
        }
    }

    </script>
    
    
    <button style="border: none; border-radius: 3px;" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product</button>

    <p></p>
    <h5 style="font-family: 'Unna', cursive; color: #313131; font-size: 16px;">Sesi terakhir login: {{ last_login }}</h5>

    <p></p>

</body>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block content %}  

<head>    
    <meta charset="UTF-8">
    <title style="font-family: 'Mulish';">Register</title>

    <style>
        body {
            font-family: "Mulish";
            background-color: #ebe6e4;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .login {
            background-color: #fffdfc;
            border-radius: 5px;
            box-shadow: 0 0 10px 292727(0, 0, 0, 0.1);
            padding: 20px;
            max-width: 800px;
            width: 100%;
            text-align: center;
        }

        .login-container h1 {
            margin-bottom: 20px;
        }

        .login-form {
            text-align: left;
            padding: auto;
        }

        .form-group {
            margin-bottom: 15px;
            padding: auto;
        }

        .form-group label {
            display: block;
            margin-bottom: 5px;
        }

        .form-group input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .form-group button {
            background-color: #007BFF;

        }


        </style>
        <link href="https://fonts.googleapis.com/css2?family=Mulish&family=Unna:wght@700&display=swap" rel="stylesheet">


</head>

<body>
    <div class = "login">
        
        <h1>Register</h1>  

        <div class="login-form" style="text-align: center;">
            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input type="submit" name="submit" value="Daftar"/></td>  
                    </tr>  
                </table>  
            </form>
        </div>
        
        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}

    </div>  
</body>
{% endblock content %}